repos:
  - repo: local
    hooks:
      - id: clippy
        name: clippy
        entry: just clippy
        language: system
        pass_filenames: false
        always_run: true
  - repo: local
    hooks:
      - id: fmt
        name: fmt
        entry: just fmt
        language: system
        pass_filenames: false
        always_run: true
