name: ci_cd

on:
  pull_request:
    branches: [ "main" ]
  push:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  testing:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v3
      - name: Add clippy
        run: rustup component add clippy
      - name: Build
        run: cargo build --verbose
      - name: Clippy check
        run: cargo clippy --all-targets --all-features -- -D warnings
